name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download NuGet
        id: download-nuget
        run: |
          sudo curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

      - name: Build the solution
        run: dotnet build "ISRUApi.sln" -c Release

      - name: Find zip
        id: find-zip
        run: |
          echo "zip=$(ls -1 dist/ISRUApi-*.zip | head -n 1)" >> $GITHUB_ENV
          echo "artifact_name=ISRUApiRelease" >> $GITHUB_ENV

      - name: Upload zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.zip }}

      - name: Find NuGet package
        id: find-nupkg
        run: |
          echo "nupkg=$(ls -1 nuget/ISRUApi.*.nupkg | head -n 1)" >> $GITHUB_ENV
          echo "artifact_name=ISRUApiNuGet" >> $GITHUB_ENV

      - name: Upload NuGet package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.nupkg }}

